name: Build and deploy

on:
  push:
    branches: [main]
  schedule:
    - cron: "30 1,3,5,7,9 * * *"
  workflow_dispatch:

env:
  JS: ${{ secrets.JS }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      # 安装依赖
      - name: Install dependencies
        run: |
          ls
          echo "${JS}" > ./index.js
          ls
          npm install
          npm run start
